version: '2.1'
services:

  tarantool:
    container_name: tarantool
    build: .
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: secret-cluster-cookie
    ports:
      - "3303:3301"