version: '3.8'
services:

  tarantool-one-node:
    container_name: tarantool-one-node
    build: .
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: secret-cluster-cookie
    ports:
      - "3301:3301"